  # Tested on docker-compose version 1.28.6, build 5db8d86f

version: '3'
services:
  redis_cache_store:
    image: redis:3.2.12
    network_mode: host
    volumes: 
      - storaji_redis_cache:/data
  mysql:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    network_mode: host
    volumes: 
      - storaji_mysql:/var/lib/mysql

volumes:
  storaji_redis_cache:
  storaji_mysql: